MyWebApp.MVC/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebApp.Entities.Dtos.HomePageSliderDtos;
using MyWebApp.Service.Abstract;
using MyWebApp.Shared.Utilities.ComplexTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SliderController : Controller
    {
        private readonly IHomePageSliderService _homePageSliderService;

        public SliderController(IHomePageSliderService homePageSliderService)
        {
            _homePageSliderService = homePageSliderService;
        }

        public async Task<IActionResult> Index()
        {
            var sliders = await _homePageSliderService.GetAll();
            if (sliders.ResultStatus == ResultStatus.Success)
            {
                return View(sliders.Data);
            }
            if (sliders.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var slider = await _homePageSliderService.Get(id);
            if (slider.ResultStatus == ResultStatus.Success)
            {
                return View(slider.Data);
            }
            if (slider.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var slider = await _homePageSliderService.GetUpdateDto(id);
            if (slider.ResultStatus == ResultStatus.Success)
            {
                return View(slider.Data);
            }
            if (slider.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HomePageSliderUpdateDto homePageSliderUpdateDto)
        {
            if (ModelState.IsValid)
            {
                await _homePageSliderService.Update(homePageSliderUpdateDto, "Hasan Erdal");
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(HomePageSliderAddDto homePageSliderAddDto)
        {
            if (ModelState.IsValid)
            {
                await _homePageSliderService.Add(homePageSliderAddDto, "Hasan Erdal");
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> HardDelete(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var slider = await _homePageSliderService.Get(id);
            if (slider.ResultStatus == ResultStatus.Success)
            {
                return View(slider.Data);
            }
            if (slider.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }

        public async Task<IActionResult> DoHardDelete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }
            await _homePageSliderService.HardDelete(id);
            return RedirectToAction("Index");
        }
    }
}

MyWebApp.MVC/Areas/Admin/Views/Slider/Add.cshtml
@model MyWebApp.Entities.Dtos.HomePageSliderDtos.HomePageSliderAddDto

@{
    ViewBag.Title = "Slider Ekleme";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Slider">Slider Listesi</a></li>
    <li class="breadcrumb-item">Yeni Slider Ekleme</li>
</ol>
<hr />
<form method="post" asp-action="Add">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShortDescription"></label>
        <input class="form-control" asp-for="ShortDescription" />
        <span asp-validation-for="ShortDescription" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LongDescription"></label>
        <textarea asp-for="LongDescription" class="form-control" style="min-height:500px;" rows="10" id="editor">
        </textarea>
        <span asp-validation-for="LongDescription"></span>
    </div>
    <div class="form-group">
        <div class="offset-lg-1 col-lg-10">
            <button class="btn btn-success" type="submit"><i class="far fa-save"></i> Bilgileri Kaydet</button>
        </div>
    </div>
</form>
<a asp-action="Index" class="btn btn-danger"><i class="fas fa-undo"></i> Listeye Dön</a>

MyWebApp.MVC/Areas/Admin/Views/Slider/Details.cshtml
@model MyWebApp.Entities.Dtos.HomePageSliderDtos.HomePageSliderDto

@{
    ViewBag.Title = "Slider Detayları";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Slider">Slider Listesi</a></li>
    <li class="breadcrumb-item">Slider Detayları</li>
</ol>
<hr />
<div>
    <h2 class="text-center">Slider Detayları</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Başlık
        </dt>
        <dd>
            @Model.HomePageSlider.Title
        </dd>

        <dt>
            Kısa İçerik
        </dt>
        <dd>
            @Model.HomePageSlider.ShortDescription
        </dd>

        <dt>
            Silindi mi?
        </dt>
        <dd>
            @Model.HomePageSlider.IsDeleted
        </dd>

        <dt>
            Aktif mi?
        </dt>
        <dd>
            @Model.HomePageSlider.IsActive
        </dd>

        <dt>
            Oluşturulma Zamanı
        </dt>
        <dd>
            @Model.HomePageSlider.CreatedTime
        </dd>

        <dt>
            Oluşturan
        </dt>
        <dd>
            @Model.HomePageSlider.CreatedByName
        </dd>

        <dt>
            Düzenlenme Zamanı
        </dt>
        <dd>
            @Model.HomePageSlider.ModifiedTime
        </dd>

        <dt>
            Düzenleyen
        </dt>
        <dd>
            @Model.HomePageSlider.ModifiedByName
        </dd>

        <dt>İçerik</dt>
        <dd>
            @Html.Raw(Model.HomePageSlider.LongDescription)
        </dd>
    </dl>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a asp-action="Edit" asp-controller="Slider" asp-area="Admin" asp-route-id="@Model.HomePageSlider.Id" class="btn btn-primary"><i class="fas fa-edit"></i> Bilgileri Düzenle</a>
    <a class="btn btn-warning" asp-action="Index" asp-controller="Slider" asp-area="Admin"><i class="fas fa-undo"></i> Listeye Dön</a>
</div>

MyWebApp.MVC/Areas/Admin/Views/Slider/Edit.cshtml
@model MyWebApp.Entities.Dtos.HomePageSliderDtos.HomePageSliderUpdateDto

@{
    ViewBag.Title = "Slider Bilgileri Düzenleme";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Slider">Slider Listesi</a></li>
    <li class="breadcrumb-item">Slider Bilgileri Düzenleme</li>
</ol>
<hr />
<form method="post" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShortDescription"></label>
        <input class="form-control" asp-for="ShortDescription" />
        <span asp-validation-for="ShortDescription" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsActive" class="form-check-label"></label>
        <input type="checkbox" asp-for="IsActive" />
        <span asp-validation-for="IsActive" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsDeleted"></label>
        <input asp-for="IsDeleted" type="checkbox" />
        <span asp-validation-for="IsDeleted"></span>
    </div>
    <div class="form-group">
        <label asp-for="LongDescription"></label>
        <textarea asp-for="LongDescription" class="form-control" style="min-height:500px;" rows="10" id="editor">
        </textarea>
        <span asp-validation-for="LongDescription"></span>
    </div>
    <div class="form-group">
        <div class="offset-lg-1 col-lg-10">
            <button class="btn btn-success" type="submit"><i class="far fa-save"></i> Bilgileri Kaydet</button>
        </div>
    </div>
</form>
<a asp-action="Index" class="btn btn-danger"><i class="fas fa-undo"></i> Listeye Dön</a>

@section Scripts{
    <script>

    </script>
}

MyWebApp.MVC/Areas/Admin/Views/Slider/HardDelete.cshtml
@model MyWebApp.Entities.Dtos.HomePageSliderDtos.HomePageSliderDto

@{
    ViewBag.Title = "Slider Silme";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Slider">Slider Listesi</a></li>
    <li class="breadcrumb-item">Slider Silme</li>
</ol>
<hr />
<div>
    <h2 class="text-center">Slider Detayları</h2>
    <hr />
    <h3>@Model.HomePageSlider.Title başlıklı slider alanını veritabanından silmek istiyor musunuz?</h3>
    <dl class="dl-horizontal">
        <dt>
            Başlık
        </dt>
        <dd>
            @Model.HomePageSlider.Title
        </dd>

        <dt>
            Kısa İçerik
        </dt>
        <dd>
            @Model.HomePageSlider.ShortDescription
        </dd>

        <dt>
            Silindi mi?
        </dt>
        <dd>
            @Model.HomePageSlider.IsDeleted
        </dd>

        <dt>
            Aktif mi?
        </dt>
        <dd>
            @Model.HomePageSlider.IsActive
        </dd>

        <dt>
            Oluşturulma Zamanı
        </dt>
        <dd>
            @Model.HomePageSlider.CreatedTime
        </dd>

        <dt>
            Oluşturan
        </dt>
        <dd>
            @Model.HomePageSlider.CreatedByName
        </dd>

        <dt>
            Düzenlenme Zamanı
        </dt>
        <dd>
            @Model.HomePageSlider.ModifiedTime
        </dd>

        <dt>
            Düzenleyen
        </dt>
        <dd>
            @Model.HomePageSlider.ModifiedByName
        </dd>

        <dt>İçerik</dt>
        <dd>
            @Html.Raw(Model.HomePageSlider.LongDescription)
        </dd>
    </dl>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a asp-action="DoHardDelete" asp-controller="Slider" asp-area="Admin" asp-route-id="@Model.HomePageSlider.Id" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Bilgileri Sil</a>
    <a class="btn btn-warning" asp-action="Index" asp-controller="Slider" asp-area="Admin"><i class="fas fa-undo"></i> Listeye Dön</a>
</div>

MyWebApp.MVC/Areas/Admin/Views/Slider/Index.cshtml
@model MyWebApp.Entities.Dtos.HomePageSliderDtos.HomePageSliderListDto

@{
    ViewBag.Title = "Slider";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item">Slider Listesi</li>
</ol>
<hr />
@if (Model.ResultStatus == ResultStatus.Success)
{
    <h2 class="text-center">Slider Listesi</h2>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Slider&nbsp; <a asp-action="Add" class="btn btn-success"><i class="fas fa-plus"></i> Slider Ekle</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="myDataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Başlık</th>
                            <th>Kısa İçerik</th>
                            <th>İçerik</th>
                            <th>Silindi Mi?</th>
                            <th>Aktif Mi?</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Oluşturan</th>
                            <th>Düzenlenme Tarihi</th>
                            <th>Düzenleyen</th>
                            <th>İşlem</th>
                        </tr>
                    </thead>
                    <tfoot class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Başlık</th>
                            <th>Kısa İçerik</th>
                            <th>İçerik</th>
                            <th>Silindi Mi?</th>
                            <th>Aktif Mi?</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Oluşturan</th>
                            <th>Düzenlenme Tarihi</th>
                            <th>Düzenleyen</th>
                            <th>İşlem</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model.HomePageSliders)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.ShortDescription</td>
                                <td>İçerik kısmını görmek için detaylara gidiniz.</td>
                                <td>@item.IsDeleted</td>
                                <td>@item.IsActive</td>
                                <td>@item.CreatedTime.ToShortDateString()</td>
                                <td>@item.CreatedByName</td>
                                <td>@item.ModifiedTime.ToShortDateString()</td>
                                <td>@item.ModifiedByName</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a class="btn btn-primary" asp-area="Admin" asp-controller="Slider" asp-action="Edit" asp-route-id="@item.Id" title="Düzenle"><i class="fas fa-edit"></i></a>
                                        <a class="btn btn-secondary" asp-area="Admin" asp-controller="Slider" asp-action="Details" asp-route-id="@item.Id" title="Detayları İncele"><i class="fas fa-info-circle"></i></a>
                                        <a class="btn btn-danger" asp-area="Admin" asp-controller="Slider" asp-action="HardDelete" asp-route-id="@item.Id" title="Veritabanından Sil"><i class="fas fa-trash-alt"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}