MyWebApp.MVC/Areas/Admin/Controllers/SiteIdentityController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Html;
using MyWebApp.Entities.Dtos.SiteIdentityDtos;
using MyWebApp.Service.Abstract;
using MyWebApp.Shared.Utilities.ComplexTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.AspNetCore.Authorization;

namespace MyWebApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SiteIdentityController : Controller
    {
        private readonly ISiteIdentityService _siteIdentityService;

        public SiteIdentityController(ISiteIdentityService siteIdentityService)
        {
            _siteIdentityService = siteIdentityService;
        }
        public async Task<IActionResult> Index()
        {
            var identity = await _siteIdentityService.Get(1);
            return View(identity.Data);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id=1)
        {
            var identity = await _siteIdentityService.GetUpdateDto(id);
            if (identity.ResultStatus == ResultStatus.Success)
            {
                return View(identity.Data);
            }
            if (identity.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SiteIdentityUpdateDto siteIdentityUpdateDto)
        {
            if (ModelState.IsValid)
            {
                await _siteIdentityService.Update(siteIdentityUpdateDto, "Hasan Erdal");
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> Details(int id = 1)
        {
            var identity = await _siteIdentityService.Get(id);
            if (identity.ResultStatus == ResultStatus.Success)
            {
                return View(identity.Data);
            }
            if (identity.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            return View();
        }
    }
}

MyWebApp.MVC/Areas/Admin/Views/SiteIdentity/Details.cshtml
@model MyWebApp.Entities.Dtos.SiteIdentityDtos.SiteIdentityDto

@{
    ViewBag.Title = "Site Kimlik Bilgileri Detaylar";
 }
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="SiteIdentity">Site Kimlik Bilgileri</a></li>
    <li class="breadcrumb-item">Site Kimlik Bilgileri Detayları</li>
</ol><hr />
<div>
    <h2 class="text-center">Site Kimlik Bilgileri</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Site Başlık
        </dt>

        <dd>
            @Model.SiteIdentity.Title
        </dd>

        <dt>
            Seo Etiketleri
        </dt>

        <dd>
            @Model.SiteIdentity.Keywords
        </dd>

        <dt>
            Site Açıklama
        </dt>

        <dd>
            @Model.SiteIdentity.Description
        </dd>

        <dt>
            Site Logo
        </dt>

        <dd style="font-size:30px">
            @Html.Raw(Model.SiteIdentity.LogoFA)
        </dd>

        <dt>
            Logo Yazısı
        </dt>
        <dd>
            @Model.SiteIdentity.LogoText
        </dd>

        <dt>
            Oluşturulma Tarihi
        </dt>
        <dd>
            @Model.SiteIdentity.CreatedTime
        </dd>

        <dt>
            Oluşturan
        </dt>
        <dd>
            @Model.SiteIdentity.CreatedByName
        </dd>

        <dt>
            Düzenlenme Tarihi
        </dt>
        <dd>
            @Model.SiteIdentity.ModifiedTime
        </dd>

        <dt>
            Düzenleyen
        </dt>
        <dd>
            @Model.SiteIdentity.ModifiedByName
        </dd>
    </dl>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a asp-action="Edit" asp-controller="SiteIdentity" asp-area="Admin" asp-route-id="@Model.SiteIdentity.Id" class="btn btn-primary"><i class="fas fa-edit"></i> Bilgileri Düzenle</a>
    <a class="btn btn-warning" asp-action="Index" asp-controller="SiteIdentity" asp-area="Admin"><i class="fas fa-info-circle"></i> Listeye Dön</a>
</div>
    

MyWebApp.MVC/Areas/Admin/Views/SiteIdentity/Edit.cshtml
@model MyWebApp.Entities.Dtos.SiteIdentityDtos.SiteIdentityUpdateDto
@{
    ViewBag.Title = "Site Kimlik Bilgileri Düzenleme";
    Layout = "_Layout";
}
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="SiteIdentity">Site Kimlik Bilgileri</a></li>
    <li class="breadcrumb-item">Site Kimlik Bilgileri Düzenleme</li>
</ol><hr />
<h2 class="text-center">Site Kimlik Bilgileri Düzenleme</h2>
<form method="post" class="" asp-controller="SiteIdentity" asp-area="Admin" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title" />
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Keywords"></label>
        <input class="form-control" asp-for="Keywords" />
        <span asp-validation-for="Keywords"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description"/>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="LogoFA"></label>&nbsp;@Html.Raw(Model.LogoFA)
        <input class="form-control" asp-for="LogoFA" />
        <span asp-validation-for="LogoFA"></span>
    </div>
    <div class="form-group">
        <label asp-for="LogoText"></label>
        <input class="form-control" asp-for="LogoText" />
        <span asp-validation-for="LogoText"></span>
    </div>
    <input hidden type="checkbox" asp-for="IsActive" />
    <input hidden type="checkbox"  asp-for="IsDeleted" />
    <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
            <button type="submit" class="btn btn-success"><i class="far fa-save"></i> Bilgileri Kaydet</button>
        </div>
    </div>
</form>
<a asp-area="Admin" asp-controller="SiteIdentity" asp-action="Index" class="btn btn-warning"><i class="fas fa-angle-double-left"></i> Listeye Dön</a>

MyWebApp.MVC/Areas/Admin/Views/SiteIdentity/Index.cshtml
@model MyWebApp.Entities.Dtos.SiteIdentityDtos.SiteIdentityDto

@{ 
    ViewBag.Title = "Site Kimlik Bilgileri";
    Layout = "_Layout";
}
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item">Site Kimlik Bilgileri</li>
</ol><hr />
@if (Model.ResultStatus == ResultStatus.Success)
{
    <h2 class="text-center">Site Kimlik Bilgileri</h2>
    <table class="table table-responsive-lg table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Başlık</th>
                <th>Etiketler</th>
                <th>Açıklama</th>
                <th>LogoFA</th>
                <th>Logo Yazısı</th>
                <th>Oluşturulma Tarihi</th>
                <th>Oluşturan</th>
                <th>Düzenlenme Tarihi</th>
                <th>Düzenleyen</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tfoot class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Başlık</th>
                <th>Etiketler</th>
                <th>Açıklama</th>
                <th>LogoFA</th>
                <th>Logo Yazısı</th>
                <th>Oluşturulma Tarihi</th>
                <th>Oluşturan</th>
                <th>Düzenlenme Tarihi</th>
                <th>Düzenleyen</th>
                <th>İşlem</th>
            </tr>
        </tfoot>
        <tbody>
            <tr>
                <td>@Model.SiteIdentity.Id</td>
                <td>@Model.SiteIdentity.Title</td>
                <td>@Model.SiteIdentity.Keywords</td>
                <td>@Model.SiteIdentity.Description</td>
                <td>@Html.Raw(Model.SiteIdentity.LogoFA)</td>
                <td>@Model.SiteIdentity.LogoText</td>
                <td>@Model.SiteIdentity.CreatedTime.ToShortDateString()</td>
                <td>@Model.SiteIdentity.CreatedByName</td>
                <td>@Model.SiteIdentity.ModifiedTime.ToShortDateString()</td>
                <td>@Model.SiteIdentity.ModifiedByName</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a class="btn btn-primary" asp-area="Admin" asp-controller="SiteIdentity" asp-action="Edit" asp-route-id="@Model.SiteIdentity.Id" title="Düzenle"><i class="fas fa-edit"></i></a>
                        <a class="btn btn-secondary" asp-area="Admin" asp-controller="SiteIdentity" asp-action="Details" asp-route-id="@Model.SiteIdentity.Id" title="Detaylı İncele"><i class="fas fa-info-circle"></i></a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
}