MyWebApp.MVC/Areas/Admin/Controllers/SummaryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebApp.Entities.Dtos.SummaryDtos;
using MyWebApp.Service.Abstract;
using MyWebApp.Shared.Utilities.ComplexTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SummaryController : Controller
    {
        private readonly ISummaryService _summaryService;

        public SummaryController(ISummaryService summaryService)
        {
            _summaryService = summaryService;
        }


        public async Task<IActionResult> Index()
        {
            var summary = await _summaryService.Get(1);
            if (summary.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            if (summary.ResultStatus == ResultStatus.Success)
            {
                return View(summary.Data);
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }
            var summary = await _summaryService.GetUpdateDto(id);
            if (summary.ResultStatus == ResultStatus.Error)
            {
                return NotFound();
            }
            if (summary.ResultStatus == ResultStatus.Success)
            {
                return View(summary.Data);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SummaryUpdateDto summaryUpdateDto)
        {
            if (ModelState.IsValid)
            {
                await _summaryService.Update(summaryUpdateDto,"Hasan Erdal");
                return RedirectToAction("Index");
            }
            return View(summaryUpdateDto);
        }
    }
}

MyWebApp.MVC/Areas/Admin/Views/Summary/Edit.cshtml
@model MyWebApp.Entities.Dtos.SummaryDtos.SummaryUpdateDto

@{
    ViewBag.Title = "Özet Bilgileri Düzenleme";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Summary">Özet Bilgisi</a></li>
    <li class="breadcrumb-item">Özet Bilgisi Düzenleme</li>
</ol>
<hr />
<h2 class="text-center">Özet Bilgisi Düzenleme</h2>
<form method="post" asp-action="Edit">
    <input hidden asp-for="Id" />
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" rows="5" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <input hidden asp-for="IsActive" type="checkbox" />
    <input hidden asp-for="IsDeleted" type="checkbox" />
    <div class="form-group">
        <div class="offset-lg-1">
            <button class="btn btn-success" type="submit"><i class="far fa-save"></i> Bilgileri Kaydet</button>
        </div>
    </div>
</form>
<a asp-action="Index" class="btn btn-warning"><i class="fas fa-undo"></i> Listeye Dön</a>

MyWebApp.MVC/Areas/Admin/Views/Summary/Index.cshtml
@model MyWebApp.Entities.Dtos.SummaryDtos.SummaryDto

@{
    ViewBag.Title = "Özet Bilgisi";
}

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-action="Index" asp-controller="Home">Admin</a></li>
    <li class="breadcrumb-item">Özet Bilgisi</li>
</ol>
<hr />
@if (Model.ResultStatus == ResultStatus.Success)
{
<h2 class="text-center">Özet Bilgisi</h2>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Özet
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-responsive-lg table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Özet</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Oluşturan</th>
                            <th>Düzenlenme Tarihi</th>
                            <th>Düzenleyen</th>
                            <th>İşlem</th>
                        </tr>
                    </thead>
                    <tfoot class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Özet</th>
                            <th>Oluşturulma Tarihi</th>
                            <th>Oluşturan</th>
                            <th>Düzenlenme Tarihi</th>
                            <th>Düzenleyen</th>
                            <th>İşlem</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>@Model.Summary.Id</td>
                            <td>@Model.Summary.Content</td>
                            <td>@Model.Summary.CreatedTime.ToShortDateString()</td>
                            <td>@Model.Summary.CreatedByName</td>
                            <td>@Model.Summary.ModifiedTime.ToShortDateString()</td>
                            <td>@Model.Summary.ModifiedByName</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Summary" asp-action="Edit" asp-route-id="@Model.Summary.Id" title="Düzenle"><i class="fas fa-edit"></i></a>
                                    
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}